package org.jaccept;

import org.testng.ITestResult;

public interface TestEventListener {
    public void projectStart(String name);


    public void suiteStart(String name);

    /**
     * Signals the start of a test class, eg. a test method.
     *
     * @param name The name of the test.
     */
    public void classStart(String name);

    /**
     * Signals the start of a test, eg. a test method.
     *
     * @param name The name of the test.
     */
    public void testStart(String name);

    /**
     * Description of the current test scope, eg. project, suite, .
     */
    void addDescription(String description);

    /**
     * References relevant to the current test scope.
     */
    void addReference(String reference);

    /**
     * Signals the start of a test step.
     *
     * @param stimuli        The stimuli associated with the test step
     * @param expectedResult The expected result of the stimuli
     */
    void stepStart(String stimuli, String expectedResult);

    /**
     * Signals the ending of a test step .
     */
    void stepEnd();

    /**
     * Signals a stimuli has been injected into the component under test.
     *
     * @param stimuliDescription String representation of the stimuli injected into the component under test.
     */
    void addStimuli(String stimuliDescription);

    /**
     * Signals a result has been generated by the component under test.
     *
     * @param resultDescription String representation of the stimuli injected into the component under test.
     */
    void addResult(String resultDescription);

    /**
     * Signals a fixture setup event, eg. a test event
     * @param setupDescription
     */
    void addFixture(String setupDescription);

    void testFailure(ITestResult result);

    void testSuccess(ITestResult result);

    void classFinish();

    void suiteFinish();

    void projectFinish();
}
